apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-crm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ahmadz94/demo-crm-chart.git
    targetRevision: main
    path: demo-crm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
